### ISSUE TITLE
Putting qmake and meson builds in the same github actions workflow?

### ISSUE THREAD

**Issue by dyfer** [jacktrip/jacktrip#468]
A while ago I thought about putting meson and qmake (and, possibly, in the future cmake) builds in the same gha workflow. My thinking is that this would allow easier switching between which build system we use for releases etc.
This could eventually supersede the current meson separate workflow. What do you think about this @ntonnaett?

I made two proposed workflows: [option A](https://github.com/dyfer/jacktrip/actions/runs/1670362806/workflow) and [option B](https://github.com/dyfer/jacktrip/actions/runs/1670365711/workflow). Here's a quick comparison:

**Option A** has a straightforward build configuration in the build matrix, e.g.
```yaml
system-rtaudio: false
bundled-rtaudio: true
nogui: false
weakjack: false
```
but the [build steps](https://github.com/dyfer/jacktrip/actions/runs/1670362806/workflow#L351-L399) have quite a bit of switches to support this and I'm worried this would be a burden to maintain down the road.

**Option B** specifies build configuration directly in the matrix, e.g.
```yaml
system-rtaudio: false
...
meson-config: '-Ddefault_library=static -Drtaudio:jack=disabled -Drtaudio:default_library=static -Dweakjack=true'
```
so on one hand it's more transparent in relation to the general developer documentation, but one needs to be more specific/careful when creating new build configurations. In return [build steps](https://github.com/dyfer/jacktrip/actions/runs/1670365711/workflow#L326-L338) are much shorter and the overall yaml file is shorter too.

Which option seems better?

----
Also, I noticed some fancy clang-tidy commenter in #462 that depends on the meson workflow currently. If my suggestion to unify qmake and meson builds gets eventually merged, I'd move the clang-tidy "insecure" part to a new workflow.
